#! /bin/sh

sxhkd &

bspc config border_width         1
bspc config window_gap           16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 25
bspc config adaptative_raise true

bspc config focus_follows_pointer false
bspc config pointer_follows_focus false

# move/resize window with alt + mouse
bspc config pointer_modifier mod1

## prevent focus stealing
# bspc config ignore_ewmh_focus true

bspc config pointer_action1 resize_side
bspc config pointer_action1 resize_corner
bspc config pointer_action3 move

bspc config active_border_color     "#515151"
bspc config normal_border_color '#8C8C8C'
bspc config normal_locked_border_color '#8C8C8C'
bspc config focused_border_color    "#6b85c2"
bspc config focused_locked_border_color '#28A017'
bspc config presel_border_color '#F9F9F9'
bspc config presel_feedback_color   "#b77a76"

#bspc config normal_border_color "#575863"
#bspc config active_border_color "#575863"
#bspc config focused_border_color "#DADCDE"
#bspc config presel_feedback_color "#575863"



bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Code -o desktop='^4'
bspc rule -a Firefox -o desktop='^6'
bspc rule -a TelegramDesktop -o desktop='^7'
bspc rule -a Slack -o desktop='^8'
# bspc rule -a jetbrains-phpstorm desktop='^9'
# bspc rule -a jetbrains-datagrip desktop='^0'

bspc rule -a Screenkey manage=off
bspc rule -a guake floating=on focus=on state=floating sticky=on
# bspc rule -a mplayer2 state=floating
# bspc rule -a Zathura state=tiled



if [ -x "$HOME/.config/bspwm/script_bspwm_init" ]; then
    $HOME/.config/bspwm/script_bspwm_init
fi
# if [ "$(bspc query -M | wc -l)" -eq "2" ]; then
# 	bspc monitor eDP1 -d 1 2 3
# 	bspc monitor HDMI1 -d 4 5 6 7 8 9 0
# else
#    bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0
# fi

export _JAVA_AWT_WM_NONREPARTENTING=1 & #IDEA wm fix
# toggle keyboard language de, us with alt+shift
setxkbmap -option grp:alt_shift_toggle us,ru &
wmname LG3D &
xsetroot -cursor_name left_ptr &
feh --randomize --bg-fill ~/Dropbox/Wallpapers &

#dunst -conf ~/.config/dunst/dunstrc &

# set default mouse cursor (no X)
xsetroot -cursor_name left_ptr

# compton (effects)
compton --config ~/.config/compton.conf &
nm-applet &
# compton &
#fluxgui &
guake &
slack &
firefox &
code &
# telegram-desktop &

# Launches Polybar
$HOME/.config/polybar/launch.sh &
